name: first workflow



on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:



jobs:
    deneme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/chechout@v4
            - name: Hello World
              run: |
                echo "Hello World"
                printenv
